### ISSUE TITLE
JDK11 upgrade?

### ISSUE THREAD

**Issue by NapoSky** [rpardini/adoptopenjdk-deb-installer#11]
I've currently using the repo for a while, and everytime I deploy jdk11-hotspot-installer, i'm on 11.0.8+10 version. The last one on AdoptOpenJDK is 11.0.10+9. Is it normal or am I missing something ?

Same, is there a command or a way to make an autoupgrade of the actual JDK installed on the host ? 

OS: Debian 8.11

Thanks!

**Comment by rpardini** [comment]
Hi! These are unofficial packages, I update them more or less randomly according to my own needs. 
If I find the time I'll migrate the GPG key from HW to SW and automate daily builds on Github Actions, but it's bottom-ish on my todo list.
Please look for the official AOJ packages... they are the supported/correct way to stay updated.

**Comment by rpardini** [comment]
Closing, since we now have daily-built packages for Adoptium.
