### ISSUE TITLE
OpenJ9 deb installers based on IBM/Semeru

### ISSUE THREAD

**Issue by chaos-dremel** [rpardini/adoptopenjdk-deb-installer#12]
Hi. After AdoptOpenJDK has transformed in Adoptium they've stopped to provide OpenJ9 builds and recommends to use IBM/Semeru builds. But IBM/Semeru has only [.tar.gz and .rpm builds](https://developer.ibm.com/languages/java/semeru-runtimes/downloads) and no .debs.
So, I think a lot of people really could have a use for ppa repository with new OpenJ9 deb packages.

**Comment by rpardini** [comment]
Indeed: https://github.com/rpardini/adoptium-deb-installer/blob/d471d056dd3a724f201292dd3d2c942175e0e849/generator/generate.js#L64

I haven't looked at Semeru at all since I won't be running OpenJ9 builds anytime soon, but if they provide an API, we could consider adding it back. PRs are welcome.
