### ISSUE TITLE
Adoptium Temurim 17 JRE

### ISSUE THREAD

**Issue by qualk** [rpardini/adoptopenjdk-deb-installer#20]
Could you please provide a package for Adoptium Temurim 17 JRE Hotspot? Thanks!

**Comment by rpardini** [comment]
Sure, I was thrown off by the fact 16 had no JRE.
I've added 17, 18 and 19 JRE packages, and testing 17 JRE against debian:stable, which seems to work.

**Comment by rpardini** [comment]
I'll close, but do report if you've success @qualk

**Comment by qualk** [comment]
Thank you! I'll test it on my server right away!
