### ISSUE TITLE
sha256sum mismatch OpenJDK8U-jre_x64_linux_hotspot_8u212b03.tar.gz

### ISSUE THREAD

**Issue by ieugen** [rpardini/adoptopenjdk-deb-installer#3]
Hi,
This happened during upgrade.

```
 adoptopenjdk-8-jre-hotspot-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)
Se pregătește adoptopenjdk-8-jre-hotspot-installer (201904201617~8u212b03+aarch64~8u191b12) ...
Installing for arch 'amd64'...
Installing from local file /var/cache/adoptopenjdk-8-jre-hotspot-installer/OpenJDK8U-jre_x64_linux_hotspot_8u212b03.tar.gz
Checking SHA256 checksum: 
AdoptOpenJDK JRE 8 with Hotspot is NOT installed: sha256sum mismatch OpenJDK8U-jre_x64_linux_hotspot_8u212b03.tar.gz
dpkg: error processing package adoptopenjdk-8-jre-hotspot-installer (--configure):
 installed adoptopenjdk-8-jre-hotspot-installer package post-installation script subprocess returned error exit status 1
```

**Comment by rpardini** [comment]
That is wierd. Please help me debug, send me the results of
```
sha256sum /var/cache/adoptopenjdk-8-jre-hotspot-installer/OpenJDK8U-jre_x64_linux_hotspot_8u212b03.tar.gz
```
I expected it to be `74daf0b77a7fd679cbb3a6228e0efa8c4a90b7664aa057f211e34bbfb38640fb`. 
If it is not, please remove the file and try again, eg (`rm /var/cache/adoptopenjdk-8-jre-hotspot-installer/OpenJDK8U-jre_x64_linux_hotspot_8u212b03.tar.gz`) -- in that case I got to understand how you got a corrupted file there in the first place, do you have any idea? (maybe interrupted download?)

**Comment by ieugen** [comment]
Hi, 

I managed to fix it before I saw you message. I apt clean-ed the local packages and removed the failing package.

I've tried again and now it works ok. So this is no longer an issue. I don't know what could have caused this. 

Thanks,
