### ISSUE TITLE
Use `sudo tee` to add source on Debian

### ISSUE THREAD

**Issue by hypescript** [rpardini/adoptopenjdk-deb-installer#6]
Using `sudo tee` instead of output redirect will let you to run the whole sequence of actions as an unprivileged user (with sudo, naturally). I.e. instead of
```
echo 'deb https://rpardini.github.io/adoptopenjdk-deb-installer stable main' > /etc/apt/sources.list.d/rpardini-aoj.list 
```
use
```
echo 'deb https://rpardini.github.io/adoptopenjdk-deb-installer stable main' | sudo tee /etc/apt/sources.list.d/rpardini-aoj.list 
```

**Comment by rpardini** [comment]
A pull request would be awesome.

**Comment by rpardini** [comment]
I see your PR on your own repo. Could you send it to me? Thanks!
