### ISSUE TITLE
Installer-based method makes apt-mirror useless

### ISSUE THREAD

**Issue by rschr** [rpardini/adoptopenjdk-deb-installer#7]
I don't know whether this is observed all over the world, but where I live, the download rates for the adoptopenjdk files from GitHub/Amazon AWS now consistently seem to be in the two-digit kB/s range, and for anyone with more than one machine needing the same packages I guess it would usually be a good idea to set up one machine acting as an apt-mirror for this PPA. But with the installer-based update method, the apt-mirror would only mirror the installer, and so even if every machine would use the mirrored PPA, it still would trigger the complete JDK download from GitHub/Amazon AWS again, and nothing would be gained. 

Until there hopefully will be a solution for the slow downloads as such at some point in time, I'd like to at least minimize the impact... Is there perhaps a not-too-complex solution I just haven't thought about?

**Comment by rpardini** [comment]
Use the official DEB packages, which are full JDK binaries and not downloaders/installers like this one. And, they're official. https://medium.com/adoptopenjdk/adoptopenjdk-rpm-and-deb-files-7003ba38144e

**Comment by rschr** [comment]
People don't install software from package repositories because they can't find the DEB packages, they install from package repositories because these are the only way to get automatic updates for software which isn't in the official repositories, without having to keep actively watching out for new releases...

**Comment by rpardini** [comment]
Fail to see your point. There are two repos: this one, unofficial, which is an installer package repository; and the official one, which contains the JDK binaries, and solves your original problem.

**Comment by rschr** [comment]
Wow, can't remember the last time I've been that slow on the uptake. Thanks for the patience!
